### ISSUE TITLE
Specify desired unit when formatting

### ISSUE THREAD

**Issue by mecampbellsoup** [Rockhopper-Technologies/prefixed#7]
Is it possible to do something like `Float(10_000_000_000)` (10 billion), and ask for that to be formatted as a specific unit, e.g. `Ti`?

My use case is for object storage quota/limit which tends to be a relatively large figure. However, usage isn't necessarily very high (e.g. I uploaded a single 512MB file to my object storage bucket) but nonetheless I want to compare "quota" vs. "used" in the same units of `Ti` to display a % utilization figure.

**Comment by avylove** [comment]
No, you can't specify the unit. The justification is if you know the unit, then you can just do a quick conversion. For example to convert to Ti, you would just do something like ``value / 2 ** 40``.

That said, if your goal is to calculate the percent utilization, that doesn't really need units since units are just for formatting. To get utilization you would just divide the ``float`` or ``prefixed.Float`` values like normal. ``prefixed.Float`` objects behave just like ``float`` objects until you format them as strings.
